# Variables communes à tous les switches
---
ansible_user: admin_cisco
ansible_password: cyna-bsi2025
ansible_become: yes
ansible_become_method: enable
ansible_become_password: cyna-bsi2025
ansible_network_os: ios
ansible_connection: network_cli
