---

# Tâches principales du rôle distrib_switch
- name: Créer les VLANs
  vars:
    vlan_lines: |
      {% set l = [] %}
      {% for vlan in vlans %}
      {%   set _ = l.append('vlan ' ~ vlan.id) %}
      {%   set _ = l.append(' name ' ~ vlan.name) %}
      {% endfor %}
      {{ l }}
  ios_config:
    lines: "{{ vlan_lines }}"
  when: vlans is defined

- name: Configurer les interfaces trunk (si définies)
  cisco.ios.ios_config:
    lines:
      - switchport trunk encapsulation dot1q
      - switchport mode trunk
      - switchport trunk allowed vlan {{trunk_vlans}}
    parents: "interface {{ item }}"
  loop: "{{ trunk_ports | default([]) }}"
  when: trunk_ports is defined

- name: Générer les ports pour le VLAN 10
  set_fact:
    vlan10_ports: "{{ vlan10_ports | default([]) + [ item ] }}"
  when: item.access.vlan == 10
  loop: "{{ vlan_ports | default([]) | selectattr('access.vlan', 'equalto', 10) | list }}"

- name: Générer les ports pour le VLAN 20
  set_fact:
    vlan20_ports: "{{ vlan20_ports | default([]) + [ item ] }}"
  when: item.access.vlan == 20
  loop: "{{ vlan_ports | default([]) | selectattr('access.vlan', 'equalto', 20) | list }}"

- name: Générer les ports pour le VLAN 30
  set_fact:
    vlan30_ports: "{{ vlan30_ports | default([]) + [ item ] }}"
  when: item.access.vlan == 30
  loop: "{{ vlan_ports | default([]) | selectattr('access.vlan', 'equalto', 30) | list }}"

- name: Générer les ports pour le VLAN 40
  set_fact:
    vlan40_ports: "{{ vlan40_ports | default([]) + [ item ] }}"
  when: item.access.vlan == 40
  loop: "{{ vlan_ports | default([]) | selectattr('access.vlan', 'equalto', 40) | list }}"

- name: Configurer les interfaces access VLAN 10
  cisco.ios.ios_l2_interfaces:
    config: "{{ vlan10_ports }}"
  when: vlan10_ports is defined

- name: Configurer les interfaces access VLAN 20
  cisco.ios.ios_l2_interfaces:
    config: "{{ vlan20_ports }}"
  when: vlan20_ports is defined

- name: Configurer les interfaces access VLAN 30
  cisco.ios.ios_l2_interfaces:
    config: "{{ vlan30_ports }}"
  when: vlan30_ports is defined

- name: Configurer les interfaces access VLAN 40
  cisco.ios.ios_l2_interfaces:
    config: "{{ vlan40_ports }}"
  when: vlan40_ports is defined

- name: Activer le chiffrement des mots de passe
  ios_config:
    lines:
      - service password-encryption

- name: Créer l'ACL pour autoriser le SSH
  ios_config:
    lines:
      - ip access-list standard ACL-SSH
      - permit {{ ansible_server_ip }} 0.0.0.0
      - permit {{ ssh_vlan_subnet }}
      - deny any

- name: Appliquer l'ACL sur les lignes VTY
  ios_config:
    lines:
      - access-class ACL-SSH in
    parents: line vty 0 15

- name: Désactiver les serveurs HTTP et HTTPS
  ios_config:
    lines:
      - no ip http server
      - no ip http secure-server

- name: Définir la gateway par défaut
  ios_config:
    lines:
      - ip default-gateway {{ default_gateway }}
  when: default_gateway is defined

- name: Configurer SNMP v2c
  ios_config:
    lines:
      - snmp-server community {{ snmp_ro }} RO
      - snmp-server community {{ snmp_rw }} RW
      - snmp-server host {{ snmp_host }} {{ snmp_ro }}
      - snmp-server enable traps
  when: snmp_ro is defined and snmp_rw is defined and snmp_host is defined

- name: Sauvegarder la configuration
  ios_config:
    save_when: always
  notify: save config
