---
# tasks file for distrib_switch
# Ce fichier inclut les tâches nécessaires pour configurer les switches Distribution Cisco
# Il est inclus dans le playbook principal pour la configuration des switches Distribution

# Sauvegarde de la configuration pour distrib_switch
- name: Sauvegarder la configuration
  ios_config:
    save_when: always
  notify: save config
