---
- name: Configuration complète du switch Cisco
  hosts: SWITCHES
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:

    - name: Générer la liste des interfaces pour les VLAN
      set_fact:
        vlan_ports:
          - { name: "GigabitEthernet0/2", mode: access, access: { vlan: 20 } }
          - { name: "GigabitEthernet0/3", mode: access, access: { vlan: 20 } }
          - { name: "GigabitEthernet1/0", mode: access, access: { vlan: 30 } }
          - { name: "GigabitEthernet1/1", mode: access, access: { vlan: 30 } }
          - { name: "GigabitEthernet1/2", mode: access, access: { vlan: 20 } }
          - { name: "GigabitEthernet1/3", mode: access, access: { vlan: 20 } }
          - { name: "GigabitEthernet2/0", mode: access, access: { vlan: 20 } }
          - { name: "GigabitEthernet2/1", mode: access, access: { vlan: 20 } }
          - { name: "GigabitEthernet2/2", mode: access, access: { vlan: 20 } }
          - { name: "GigabitEthernet2/3", mode: access, access: { vlan: 20 } }
          - { name: "GigabitEthernet3/0", mode: access, access: { vlan: 20 } }
          - { name: "GigabitEthernet3/1", mode: access, access: { vlan: 20 } }
          - { name: "GigabitEthernet3/2", mode: access, access: { vlan: 40 } }
          - { name: "GigabitEthernet3/3", mode: access, access: { vlan: 40 } }
    - name: Configurer Gi0/2 à Gi3/3 en access VLAN 10 ou 20 ou 30 ou 40
      cisco.ios.ios_l2_interfaces:
        config: "{{ vlan_ports }}"
