---
- name: Renforcer la sécurité des switches Core
  hosts: geneve-core:paris-core
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:

    - name: Activer le chiffrement des mots de passe
      cisco.ios.ios_config:
        lines:
          - service password-encryption

    - name: Créer l'ACL pour autoriser le SSH depuis le serveur Ansible et le VLAN 10
      cisco.ios.ios_config:
        lines:
          - ip access-list standard ACL-SSH
          - permit 192.168.40.21 0.0.0.0
          - permit 192.168.10.0 0.0.0.255
          - deny any

    - name: Appliquer l'ACL sur les lignes VTY
      cisco.ios.ios_config:
        lines:
          - access-class ACL-SSH in
        parents: line vty 0 15

    - name: Désactiver les serveurs HTTP et HTTPS
      cisco.ios.ios_config:
        lines:
          - no ip http server
          - no ip http secure-server

    - name: Définir la gateway par défaut pour joindre le VLAN 10
      cisco.ios.ios_config:
        lines:
          - ip default-gateway 192.168.40.1
