---
- name: Renforcer la sécurité des switches de distribution
  hosts: geneve-distrib:paris-distrib
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:

    - name: Activer le chiffrement des mots de passe
      cisco.ios.ios_config:
        lines:
          - service password-encryption

    - name: Créer l'ACL SSH pour les hôtes autorisés
      cisco.ios.ios_config:
        lines: >-
          {{
            ['ip access-list standard ACL-SSH'] +
            ssh_acl_hosts | map('regex_replace', '^(.*)$', 'permit \\1') | list +
            ['deny any']
          }}

    - name: Appliquer l'ACL SSH sur les lignes VTY
      cisco.ios.ios_config:
        lines:
          - access-class ACL-SSH in
        parents: line vty 0 15

    - name: Désactiver les serveurs HTTP/HTTPS
      cisco.ios.ios_config:
        lines:
          - no ip http server
          - no ip http secure-server

    - name: Définir la gateway par défaut
      cisco.ios.ios_config:
        lines:
          - ip default-gateway {{ default_gateway }}
