---
# Ansible Playbook pour la configuration des switches Core Cisco
# Ce playbook inclut les rôles et les tâches nécessaires pour configurer les switches Core
# Tâches principales du rôle core_switch
- include_tasks: vlans.yml
- include_tasks: trunks.yml
- include_tasks: securite.yml
- include_tasks: snmp.yml
- include_tasks: save.yml
