---
- name: Sauvegarder la configuration (copy run start)
  hosts: SWITCHES
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios

  tasks:
    - name: Sauvegarder la configuration courante dans la startup-config
      ios_config:
        save_when: always
