---
- name: Configuration complète du switch Cisco
  hosts: geneve-distrib:paris-distrib
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:

    - name: Créer les VLANs
      vars:
        vlan_lines: |
          {% set l = [] %}
          {% for vlan in vlans %}
          {%   set _ = l.append('vlan ' ~ vlan.id) %}
          {%   set _ = l.append(' name ' ~ vlan.name) %}
          {% endfor %}
          {{ l }}
      ios_config:
        lines: "{{ vlan_lines }}"

    - name: Configurer les interfaces trunk (si définies)
      cisco.ios.ios_config:
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - switchport trunk allowed vlan {{trunk_vlans}}
        parents: "interface {{ item }}"
      loop: "{{ trunk_ports | default([]) }}"
      when: trunk_ports is defined

    - name: Générer les ports pour le VLAN 10
      set_fact:
        vlan10_ports: "{{ vlan10_ports | default([]) + [ item ] }}"
      when: item.access.vlan == 10
      loop: "{{ vlan_ports | default([]) | selectattr('access.vlan', 'equalto', 10) | list }}"

    - name: Générer les ports pour le VLAN 20
      set_fact:
        vlan20_ports: "{{ vlan20_ports | default([]) + [ item ] }}"
      when: item.access.vlan == 20
      loop: "{{ vlan_ports | default([]) | selectattr('access.vlan', 'equalto', 20) | list }}"

    - name: Générer les ports pour le VLAN 30
      set_fact:
        vlan30_ports: "{{ vlan30_ports | default([]) + [ item ] }}"
      when: item.access.vlan == 30
      loop: "{{ vlan_ports | default([]) | selectattr('access.vlan', 'equalto', 30) | list }}"

    - name: Générer les ports pour le VLAN 40
      set_fact:
        vlan40_ports: "{{ vlan40_ports | default([]) + [ item ] }}"
      when: item.access.vlan == 40
      loop: "{{ vlan_ports | default([]) | selectattr('access.vlan', 'equalto', 40) | list }}"

    - name: Configurer les interfaces access VLAN 10
      cisco.ios.ios_l2_interfaces:
        config: "{{ vlan10_ports }}"
      when: vlan10_ports is defined

    - name: Configurer les interfaces access VLAN 20
      cisco.ios.ios_l2_interfaces:
        config: "{{ vlan20_ports }}"
      when: vlan20_ports is defined

    - name: Configurer les interfaces access VLAN 30
      cisco.ios.ios_l2_interfaces:
        config: "{{ vlan30_ports }}"
      when: vlan30_ports is defined

    - name: Configurer les interfaces access VLAN 40
      cisco.ios.ios_l2_interfaces:
        config: "{{ vlan40_ports }}"
      when: vlan40_ports is defined